name: GuildUtilityPlugin
api: '1.21'
version: ${project.version}
main: com.clanplugin.Main
description: A Guild Utility Plugin for Bukkit
author: Lukas Kreuz

commands:
  clan:
    description: Clan utilities
    usage: /clan
