name: GuildUtilityPlugin
api-version: '1.21'
version: ${project.version}
main: com.clanplugin.Main
description: A Guild Utility Plugin for Bukkit
author: Lukas Kreuz

commands:
  clan:
    description: Clan utilities
    usage: /clan <create|invite|join|accept|decline|leave|list|version|help>
    aliases: [ c ]
